# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
os:
  - linux
  - osx
install:
  - ./travis-tool.sh install_deps
  - ./travis-tool.sh install_bioc_deps
  
repos:
  CRAN: https://cran.microsoft.com/snapshot/2019-01-12