# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'
install:
  ps: Bootstrap

# Adapt as necessary starting from here

environment:
  global:
    WARNINGS_ARE_ERRORS: 0
    PKGTYPE: win.binary 
    version: '1.1.{build}'
  access_token:
    secure: Vzu5ovt/88zxAaYQTBuGnP/Bj6jMB8glFakz3PMKBZktZ0ii6+TDVAks1aWHzz9O  
  
  matrix:
  - R_VERSION: 3.6.1
    R_ARCH: x64
    GCC_PATH: mingw_64

matrix:
  fast_finish: true

build_script:
  - travis-tool.sh install_deps


test_script:
  - travis-tool.sh run_tests






on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits

  - path: 'IDBac\dist\*.exe'
    name: app
  


for: 
-
  branches:
    only:
      - master
  
  before_test:
    - Rscript -e "install.packages('desc', repos = 'http://cran.rstudio.com')"
    - git checkout master
    - Rscript -e "list.files(pattern = 'DESCRIPTION', ignore.case = T, recursive = F, full.names = T)"
    - Rscript -e "desc::desc_set_version('%APPVEYOR_BUILD_VERSION%', list.files(pattern = 'DESCRIPTION', ignore.case = T, recursive = F))"
    - git config --global credential.helper store
    - ps: Add-Content "$HOME\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
    - git config --global user.email "cclark42@uic.edu"
    - git config --global user.name "Chase Clark"
    - git add DESCRIPTION
    - git commit -m "AppVeyor version bump; [skip appveyor]" 
    - git push origin master

  
  after_test:
    - Rscript -e "remotes::install_github('chasemc/electricShine@886ddff')"
    - Rscript -e "electricShine::buildElectricApp(appName = 'IDBac',
                   productName = 'IDBac',
                   semanticVersion = '%APPVEYOR_BUILD_VERSION%',
                   installTo = getwd(),
                   MRANdate = '2019-05-05',
                   functionName = 'run_app',
                   githubRepo = 'chasemc/IDBacApp',
                   localPath  = NULL,
                   only64 = FALSE,
                   packageName = 'IDBacApp')"
  deploy:
    on:
      branch: master        
    skip_tags: true
    tag: $(appveyor_build_version)
    description: 'Release description'
    provider: GitHub
    force_update: false
    auth_token:
      secure: 'Vzu5ovt/88zxAaYQTBuGnP/Bj6jMB8glFakz3PMKBZktZ0ii6+TDVAks1aWHzz9O'
    artifact: app           
    draft: false
    prerelease: false
  

