# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'
install:
  ps: Bootstrap

# Adapt as necessary starting from here

environment:
  global:
    WARNINGS_ARE_ERRORS: 0
    PKGTYPE: win.binary 
  
  matrix:
  - R_VERSION: 3.6.0
    R_ARCH: x64
    GCC_PATH: mingw_64

matrix:
  fast_finish: true

build_script:
  - travis-tool.sh install_deps

test_script:
  - travis-tool.sh run_tests


after_test:
  - Rscript -e "remotes::install_github('chasemc/electricShine')"
  - Rscript -e "electricShine::buildElectricApp(appName = 'IDBac',
                 productName = 'IDBac',
                 semanticVersion = '1.0.100',
                 installTo = getwd(),
                 MRANdate = '2019-05-05',
                 functionName = 'run_app',
                 githubRepo = 'chasemc/IDBacApp',
                 localPath  = NULL,
                 only64 = FALSE,
                 packageName = 'IDBacApp')"
  - ls -R

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits

  - path: 'IDBac\dist\*.exe'
    name: app


deploy:
  provider: GitHub
  auth_token:
    secure: 'Vzu5ovt/88zxAaYQTBuGnP/Bj6jMB8glFakz3PMKBZktZ0ii6+TDVAks1aWHzz9O' # your encrypted token from GitHub
  artifact: app           
  draft: false
  prerelease: false
  
